name: pr-checks

on:
  pull_request:
    paths:
      - "charts/patchmon/**"

jobs:
  helm-lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Add Helm repos needed for dependencies
        run: |
          helm repo add valkey https://valkey.io/valkey-helm/
          helm repo update

      - name: Build chart dependencies
        run: |
          helm dependency build charts/patchmon

      - name: Lint chart
        run: |
          helm lint charts/patchmon

      - name: Render templates (basic validation)
        run: |
          # Render with default values
          helm template patchmon charts/patchmon > /tmp/patchmon.yaml

      - name: kubeconform (K8s schema validation)
        shell: bash
        run: |
          set -euo pipefail
          KUBECONFORM_VERSION="0.7.0"
          OS="linux"
          ARCH="amd64"
          curl -sSL -o /tmp/kubeconform \
            "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-${OS}-${ARCH}"
          chmod +x /tmp/kubeconform
          install -m 0755 /tmp/kubeconform /usr/local/bin/kubeconform
          kubeconform -v
          kubeconform -summary -strict -ignore-missing-schemas /tmp/patchmon.yaml
